# Numpy
- Numpy is a general purpose array-processing packages. It provide a high-performance multidimensional array object and tools for working with these array. It is the fundamental packages for scientific computing with Python

# What is an Array?
- An array is a data structure that stores values of the same data type. In python ,this is the main difference arrays and lists. While python lists can contains values corresponding to different pacakges , array in python can contains only the  values corresponding to same data type

In [1]:
import numpy as np

In [2]:
my_lis=[1,2,3,4,5]
type(my_lis)

list

In [3]:
arr=np.array(my_lis)

In [5]:
type(arr)

numpy.ndarray

In [6]:
my_lis2=[1,2,3,4,5,"Ali"]

In [7]:
arr_2=np.array(my_lis2)

In [11]:
arr.shape

(5,)

In [22]:
my_lis1=[1,2,3,4,5]
my_lis2=[6,7,8,9,10]
my_lis3=[11,12,13,14,15]
arr=np.array([my_lis1,my_lis2,my_lis3])

In [23]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [16]:
arr.shape

(3, 5)

In [17]:
arr.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [18]:
arr=np.array([1,2,3,4,5,6,7,8,9])

In [19]:
arr[3]

4

In [24]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [26]:
arr[:,:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [28]:
arr[0:2,0:2]

array([[1, 2],
       [6, 7]])

In [29]:
arr[0:2,2:4]

array([[3, 4],
       [8, 9]])

In [30]:
arr[2:,4:]

array([[15]])

In [31]:
arr=np.arange(0,11)

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])