# Numpy
- Numpy is a general purpose array-processing packages. It provide a high-performance multidimensional array object and tools for working with these array. It is the fundamental packages for scientific computing with Python

# What is an Array?
- An array is a data structure that stores values of the same data type. In python ,this is the main difference arrays and lists. While python lists can contains values corresponding to different pacakges , array in python can contains only the  values corresponding to same data type

In [1]:
import numpy as np

In [2]:
my_lis=[1,2,3,4,5]
type(my_lis)

list

In [3]:
arr=np.array(my_lis)

In [5]:
type(arr)

numpy.ndarray

In [6]:
my_lis2=[1,2,3,4,5,"Ali"]

In [7]:
arr_2=np.array(my_lis2)

In [11]:
arr.shape

(5,)

In [22]:
my_lis1=[1,2,3,4,5]
my_lis2=[6,7,8,9,10]
my_lis3=[11,12,13,14,15]
arr=np.array([my_lis1,my_lis2,my_lis3])

In [23]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [16]:
arr.shape

(3, 5)

In [17]:
arr.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [18]:
arr=np.array([1,2,3,4,5,6,7,8,9])

In [19]:
arr[3]

4

In [24]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [26]:
arr[:,:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [28]:
arr[0:2,0:2]

array([[1, 2],
       [6, 7]])

In [29]:
arr[0:2,2:4]

array([[3, 4],
       [8, 9]])

In [30]:
arr[2:,4:]

array([[15]])

In [31]:
arr=np.arange(0,11)

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
np.arange(0,14,step=4)

array([ 0,  4,  8, 12])

In [34]:
np.arange(0,14)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [36]:
arr=np.arange(0,10)
arr1=arr

### Copy function() of Array

In [37]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
arr1[3:]=500

In [39]:
arr1

array([  0,   1,   2, 500, 500, 500, 500, 500, 500, 500])

In [40]:
arr

array([  0,   1,   2, 500, 500, 500, 500, 500, 500, 500])

In [41]:
arr

array([  0,   1,   2, 500, 500, 500, 500, 500, 500, 500])

In [42]:
arr<2

array([ True,  True, False, False, False, False, False, False, False,
       False])

In [43]:
arr>2

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [49]:
arr1=np.arange(0,10).reshape(5,2)
arr2=np.arange(0,10).reshape(5,2)

In [50]:
arr1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [51]:
arr2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [52]:
arr1*arr2

array([[ 0,  1],
       [ 4,  9],
       [16, 25],
       [36, 49],
       [64, 81]])

In [57]:
arr=np.ones(6).reshape(3,2)

In [58]:
arr

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [59]:
np.ones(6,dtype=int)

array([1, 1, 1, 1, 1, 1])

In [60]:
# Random distribution
np.random.rand(3,2)

array([[0.92537542, 0.80353904],
       [0.31143727, 0.4246079 ],
       [0.3509738 , 0.7105357 ]])